### ISSUE TITLE
Merging pagination into the other backbone-tastypie

### ISSUE THREAD

**Issue by maraujop** [amccloud/backbone-tastypie#2]
Hi,

I've found your project a couple days ago when I was looking into doing pagination with backbone + tastypie. Thanks for releasing it :)

I'm not sure if you know <a href="https://github.com/PaulUithol/backbone-tastypie">the other backbone-tastypie</a> project. But I think the best would be to merge your pagination into that one. It's a bigger project that includes features not supported in this one.

Right now I'm using both together, importing this library first, then the other backbone-tastypie and then changing `collection.url` there to do `url + this._getQueryString()`, but the integration feels quite hacky.

What are your thoughts? Cheers
Miguel

**Comment by amccloud** [comment]
Hey glad you found this!

I'm curious what features does that library have over this one? I'm not a huge fan of it so if anything i'd like to reevaluate and re-implement those features here if necessary.

**Comment by maraujop** [comment]
Hi Andrew,

may I ask you why re-implementing those features? It feels like reinventing the wheel to me. I've looked into both libraries' code and they are quite similar. So I would like to know what is it that you don't like from it?

To list some as an example:
- API key authentication support
- It's got an automatic GET when doing a POST and tastypie returns a Location in the Header, but no content.

My intention is to continue using that backbone-tastypie, as it's well tested and is got a bigger user base. I like the author's work, things like backbone-relational help me a lot on my daily basis. I think it's comprehensible.

Cheers,
Miguel

**Comment by amccloud** [comment]
Understandable. I created this library because I was unsatisfied with the existing solution. I've also used backbone-relational and after watching the library get bloated and unreliable for me i'm not a huge fan of how the author manages his projects.

Any particular reason api key support is needed when you can use sessions? I'm considering it but I don't see the need. As for the empty POST with tastypie see: http://django-tastypie.readthedocs.org/en/latest/resources.html#always-return-data

**Comment by amccloud** [comment]
Personally I would do something like this:

``` javascript
var authorize = function(username, key) {
    jQuery.ajaxSetup({
        beforeSend: function(xhr) {
            xhr.setRequestHeader('Authorization', 'ApiKey ' + username + ':' + key);
            return xhr;
        }
    });
};

authorize('amccloud', '204db7bcfafb2deb7506b89eb3b9b715b09905c8');
```

**Comment by maraujop** [comment]
> Understandable. I created this library because I was unsatisfied with the existing solution. I've also used backbone-relational and after watching the library get bloated and unreliable for me i'm not a huge fan of how the author manages his projects.

I will be honest. I'm not a javascript expert. But I can see the author is quite responsible with his projects, answering questions and solving bugs. 

If I don't use Backbone-relational, I don't know of any other Backbone add-on that gives this kind of functionality, so I would have to do it myself manually. Until now, I haven't seen any glitches or bloating as you mention, maybe you can give me an example or explanation about why this happens, so I can think of it. 

> Personally I would do something like this

I agree having a global ajax handler for it is a good way to solve the problem. If I were you I would mention this in your docs. As for the empty POST, I knew that Tastypie can be forced to return data, I'm using this, but others might not and will think that your library is broken because it doesn't support Tastypie's default behavior. 

In the end, both libraries are not huge, they just solve some basic Tastypie usage paradigms and yours is leaner, so you might be right with your approach. However, using the same name for the project is going to create confusion.

Finally, I've got a couple questions. I might change my mind about which library to use:
- When fetching more data you set `{add: true}` to automatically add new fetched data to the current data of the collection, which seems reasonable. What I don't know is how can I get to know what's the new data added, so I don't have to re-render the whole template for all the models, but just append the new models to the visible UI? Not sure, If my explanation is too comprehensible.
- The other thing I would like this library to have is a commonJS shim, like the one I've proposed in https://github.com/PaulUithol/backbone-tastypie/pull/21 This would allow me to use the library for javascript testing, using nodejs engine (<a href="https://github.com/visionmedia/mocha">mocha</a> allows this approach). 

Thanks for answering so fast Andrew, I appreciate your time and the discussion.

Cheers,
Miguel

**Comment by amccloud** [comment]
> I will be honest. I'm not a javascript expert. But I can see the author is quite responsible with his projects, answering questions and solving bugs.

That is true! But I'm just not a fan of how bloated it has become. Instead of having one thing that works really well you have lots of little features that work sorta. For my projects I need something reliable that isn't adding bloat every month. The other backbone-tastypie library hasn't been touched much but it was something I feared after having nightmares with backbone-relational. I also don't believe a js plugin needs to be a Django app. I want all my js plugins together.

> However, using the same name for the project is going to create confusion.

Possible. I'll consider changing the name if this becomes more apparent.

> I agree having a global ajax handler for it is a good way to solve the problem. If I were you I would mention this in your docs.

I will add it to the wiki.

> As for the empty POST, I knew that Tastypie can be forced to return data, I'm using this, but others might not and will think that your library is broken because it doesn't support Tastypie's default behavior.

Tastypie's default behavior is not for the web. Firing off an extra request for something that could have been sent to you in the previous response is bad behavior in the browser. Backbone's optimistic creation and destroying is the only thing that makes this behavior tolerable is. I may add it with a caution against it.

> When fetching more data you set {add: true} to automatically add new fetched data to the current data of the collection, which seems reasonable. What I don't know is how can I get to know what's the new data added, so I don't have to re-render the whole template for all the models, but just append the new models to the visible UI? Not sure, If my explanation is too comprehensible.

Bind to the collection's `add` event. An example if it helps: http://jsfiddle.net/SmTkg/7/ See TodoListView

> The other thing I would like this library to have is a commonJS shim, like the one I've proposed in https://github.com/PaulUithol/backbone-tastypie/pull/21 This would allow me to use the library for javascript testing, using nodejs engine (mocha allows this approach).

I use to ask other js libraries to add AMD/CommonJS support. Most don't, including Backbone and underscore. That being said the author of requirejs has built in support for loading scripts that aren't module ready in requirejs 2.0. See: https://github.com/jrburke/requirejs/wiki/Upgrading-to-RequireJS-2.0#wiki-shim Will something like that work for you?

**Comment by maraujop** [comment]
> That is true! But I'm just not a fan of how bloated it has become. Instead of having one thing that works really well you have lots of little features that work sorta. 

I do like UNIX philosophy, but it is always hard to keep scope limited.

> For my projects I need something reliable that isn't adding bloat every month. The other backbone-tastypie library hasn't been touched much but it was something I feared after having nightmares with backbone-relational. I also don't believe a js plugin needs to be a Django app. I want all my js plugins together.

I see.

> Possible. I'll consider changing the name if this becomes more apparent.

Ok.

> I will add it to the wiki.

Thanks

> Tastypie's default behavior is not for the web. Firing off an extra request for something that could have been sent to you in the previous response is bad behavior in the browser. Backbone's optimistic creation and destroying is the only thing that makes this behavior tolerable is. I may add it with a caution against it.

Agree.

> I use to ask other js libraries to add AMD/CommonJS support. Most don't, including Backbone and underscore. That being said the author of requirejs has built in support for loading scripts that aren't module ready in requirejs 2.0. See: https://github.com/jrburke/requirejs/wiki/Upgrading-to-RequireJS-2.0#wiki-shim Will something like that work for you?

Thanks for the link, very helpful, this totally works for me. 

I guess I'm closing the issue since you've convinced me :) You will hear soon from a co-worker that has found a glitch in the pagination.

Cheers,
Miguel
